### ISSUE TITLE
compile arrow client error under ubuntu,please help!

### ISSUE THREAD

**Issue by doitsjz** [angelcam/arrow-client#1]
i follow as https://github.com/angelcam/arrow-client/wiki/Quick-Start 
but finally step  :cargo build occur errors ,

my os info:
Linux version 2.6.32-38-generic (buildd@zirconium) (gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5) ) #83-Ubuntu SMP Wed Jan 4 11:13:04 UTC 2012 
openssl-1.1.0-pre3.tar.gz 
rust-1.6.0-i686-unknown-linux-gnu 
and arrow-client   is update

root@need-dev:/opt/arrow/arrow-client# cd arrow-client^C
root@need-dev:/opt/arrow/arrow-client# cargo build
   Compiling arrow-client v0.4.1 (file:///opt/arrow/arrow-client)
   Compiling kernel32-sys v0.2.1
Build failed, waiting for other jobs to finish...
failed to run custom build command for `arrow-client v0.4.1 (file:///opt/arrow/arrow-client)`
Process didn't exit successfully: `/opt/arrow/arrow-client/target/debug/build/arrow-client-40df11dd121a3327/build-script-build` (signal: 11)
--- stdout
TARGET = Some("i686-unknown-linux-gnu")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("i686-unknown-linux-gnu")
debug=true opt-level=0
HOST = Some("i686-unknown-linux-gnu")
TARGET = Some("i686-unknown-linux-gnu")
TARGET = Some("i686-unknown-linux-gnu")
HOST = Some("i686-unknown-linux-gnu")
CC_i686-unknown-linux-gnu = None
CC_i686_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("i686-unknown-linux-gnu")
TARGET = Some("i686-unknown-linux-gnu")
HOST = Some("i686-unknown-linux-gnu")
CFLAGS_i686-unknown-linux-gnu = None
CFLAGS_i686_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m32" "-o" "/opt/arrow/arrow-client/target/debug/build/arrow-client-40df11dd121a3327/out/src/net/raw/devices.o" "-c" "src/net/raw/devices.c"
ExitStatus(ExitStatus(0))
TARGET = Some("i686-unknown-linux-gnu")
TARGET = Some("i686-unknown-linux-gnu")
HOST = Some("i686-unknown-linux-gnu")
AR_i686-unknown-linux-gnu = None
AR_i686_unknown_linux_gnu = None
HOST_AR = None
AR = None
TARGET = Some("i686-unknown-linux-gnu")
running: "ar" "crus" "/opt/arrow/arrow-client/target/debug/build/arrow-client-40df11dd121a3327/out/libnet_devices.a" "/opt/arrow/arrow-client/target/debug/build/arrow-client-40df11dd121a3327/out/src/net/raw/devices.o"
ExitStatus(ExitStatus(0))
cargo:rustc-link-lib=static=net_devices
cargo:rustc-link-search=native=/opt/arrow/arrow-client/target/debug/build/arrow-client-40df11dd121a3327/out

root@need-dev:/opt/arrow/arrow-client# cargo build
   Compiling openssl-sys v0.7.6
   Compiling ws2_32-sys v0.2.1
Build failed, waiting for other jobs to finish...
failed to run custom build command for `openssl-sys v0.7.6`
Process didn't exit successfully: `/opt/arrow/arrow-client/target/debug/build/openssl-sys-f04abe5b1856e863/build-script-build` (signal: 11)
root@need-dev:/opt/arrow/arrow-client# cargo build
   Compiling ws2_32-sys v0.2.1
   Compiling kernel32-sys v0.2.1
Build failed, waiting for other jobs to finish...
failed to run custom build command for `kernel32-sys v0.2.1`
Process didn't exit successfully: `/opt/arrow/arrow-client/target/debug/build/kernel32-sys-49d5fc958bd6fccd/build-script-build` (signal: 11)
root@need-dev:/opt/arrow/arrow-client# cargo build
   Compiling ws2_32-sys v0.2.1
   Compiling kernel32-sys v0.2.1
Build failed, waiting for other jobs to finish...
failed to run custom build command for `ws2_32-sys v0.2.1`
Process didn't exit successfully: `/opt/arrow/arrow-client/target/debug/build/ws2_32-sys-48710b6d37b409eb/build-script-build` (signal: 11)
root@need-dev:/opt/arrow/arrow-client# cargo build
   Compiling openssl-sys v0.7.6
   Compiling kernel32-sys v0.2.1
   Compiling arrow-client v0.4.1 (file:///opt/arrow/arrow-client)
   Compiling ws2_32-sys v0.2.1
Build failed, waiting for other jobs to finish...
failed to run custom build command for `openssl-sys v0.7.6`
Process didn't exit successfully: `/opt/arrow/arrow-client/target/debug/build/openssl-sys-f04abe5b1856e863/build-script-build` (signal: 11)
root@need-dev:/opt/arrow/arrow-client# cargo build
   Compiling ws2_32-sys v0.2.1
   Compiling arrow-client v0.4.1 (file:///opt/arrow/arrow-client)
   Compiling openssl-sys v0.7.6
Build failed, waiting for other jobs to finish...
failed to run custom build command for `ws2_32-sys v0.2.1`
Process didn't exit successfully: `/opt/arrow/arrow-client/target/debug/build/ws2_32-sys-48710b6d37b409eb/build-script-build` (signal: 11)
root@need-dev:/opt/arrow/arrow-client#

**Comment by operutka** [comment]
Hi @doitsjz 
there is clearly a problem with compilation of native dependencies written in C. The build scripts always exit with signal 11 (i.e. segmentation fault). The build scripts are small applications also written in Rust and they use this library https://github.com/alexcrichton/gcc-rs for invoking C compiler. There might be a bug in the library or there is something wrong with your build environment.

First of all, I strongly recommend you to make sure that your build environment is OK by re-installing Rust and removing all the stuff generated by cargo:

``` bash
curl -sSf https://static.rust-lang.org/rustup.sh | sh
rm -rf ~/.cargo
```

When it is done, please run the `cargo build` again but this time add also the `-v` parameter, so the whole command will be:

``` bash
cargo build -v
```

and post here complete output generated by the command.

Your version of Ubuntu also seems a little outdated. Can you send me the exact version of Ubuntu you are running? I will try to simulate the problem in virtual environment.

**Comment by operutka** [comment]
closing for no response
