### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by cedricve** [angelcam/arrow-client#11]
Hey nice work,

Tried to compile on OSX, but get a build error.

    DEBUG = Some("true")
    running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-o" "/Users/cedricverst/Desktop/arrow-client/target/debug/build/arrow-client-df4356deccd20fff/out/src/net/raw/devices.o" "-c" "src/net/raw/devices.c"
    cargo:warning=src/net/raw/devices.c:62:19: error: use of undeclared identifier 'SIOCGIFHWADDR'
    cargo:warning=    if (ioctl(fd, SIOCGIFHWADDR, &dconf) != 0)
    cargo:warning=                  ^
    cargo:warning=src/net/raw/devices.c:64:15: error: no member named 'ifr_hwaddr' in 'struct ifreq'
    cargo:warning=    if (dconf.ifr_hwaddr.sa_family != ARPHRD_ETHER)
    cargo:warning=        ~~~~~ ^
    cargo:warning=src/net/raw/devices.c:67:26: error: no member named 'ifr_hwaddr' in 'struct ifreq'
    cargo:warning=    memcpy(buffer, dconf.ifr_hwaddr.sa_data, MAC_ADDR_SIZE);
    cargo:warning=                   ~~~~~ ^
    cargo:warning=/usr/include/secure/_string.h:65:33: note: expanded from macro 'memcpy'
    cargo:warning=  __builtin___memcpy_chk (dest, src, len, __darwin_obsz0 (dest))
    cargo:warning=                                ^~~
    cargo:warning=3 errors generated.
    exit code: 1

**Comment by operutka** [comment]
Hi @cedricve,

currently, the only supported OS is Linux because the application depends on some Linux specific syscalls for listing network interfaces. We'll probably add support for OSX and Windows in the future, however it isn't our priority right now.

You're welcome to send us a patch adding OSX support if you'd like.

**Comment by cedricve** [comment]
ok @operutka makes sense, thanks.
