### ISSUE TITLE
Doesnt work 

### ISSUE THREAD

**Issue by ghost** [angelcam/arrow-client#12]
Upon following the instructions to "turn your ARM device into Angelbox, the first line of code is sudo apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys 3CB6723D

Below in bold are the errors

**Executing: /tmp/apt-key-gpghome.dnXTxF3e6o/gpg.1.sh --keyserver hkp://keys.gnupg.net --recv-keys 3CB6723D
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.dnXTxF3e6o/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr**

**Comment by buzzdev** [comment]
@DovZA You need to install dirmngr:
`sudo apt-get install dirmngr --install-recommends`

**Comment by ghost** [comment]
that was done thanks, Angelbox still doesnt work

**Comment by buzzdev** [comment]
@DovZA What exactly is not working for you? I have it running all over the place and it works everywhere.

**Comment by ghost** [comment]
I have installed the angelcam DIY Angelbox  as laid out in the instructions on website. Insert my MAC address as required and it just searches and searches for hours

**Comment by operutka** [comment]
@DovZA your client is probably banned. We ban all clients which exceed their pairing window by more than 20 minutes, i.e. if your client is not paired and it sends requests for more than 40 minutes in a row, it'll get banned. By default, the client will try to connect to Angelcam servers only within the first 20 minutes after it starts. Restarting the client will start another 20 minutes.

If you send me your Arrow UUID, I can un-ban your client.

**Comment by buzzdev** [comment]
@operutka Hi Ondrej, that's good to know! Thanxs. Martin

**Comment by operutka** [comment]
Hi @DovZA,
is this issue still actual or can I close it?

**Comment by operutka** [comment]
Information about dirmngr has been added into our wiki. I'm closing the issue.
