### ISSUE TITLE
Cannot Compile for arm-linux-androideabi

### ISSUE THREAD

**Issue by gonzafirewall** [angelcam/arrow-client#13]
I am tryinig to make works with my Cam that is Android based but have some problems with the cargo compilation.

   Compiling arrow-client v0.6.4 (file:///home/ec2-user/arrow-client)
warning: use of deprecated item 'gcc::compile_library'
  --> build.rs:18:5
   |
18 |     gcc::compile_library("libnet_devices.a",
   |     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(deprecated)] on by default

error: failed to run custom build command for `arrow-client v0.6.4 (file:///home/ec2-user/arrow-client)`
process didn't exit successfully: `/home/ec2-user/arrow-client/target/release/build/arrow-client-4f95d8b018989ade/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("arm-linux-androideabi")
OPT_LEVEL = Some("3")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("arm-linux-androideabi")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
CC_arm-linux-androideabi = None
CC_arm_linux_androideabi = None
TARGET_CC = None
CC = None
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_arm-linux-androideabi = None
CFLAGS_arm_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "arm-linux-androideabi-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wall" "-Wextra" "-o" "/home/ec2-user/arrow-client/target/arm-linux-androideabi/release/build/arrow-client-1f4c6dab72503398/out/src/net/raw/devices.o" "-c" "src/net/raw/devices.c"
cargo:warning=src/net/raw/devices.c:25:21: fatal error: ifaddrs.h: No such file or directory
cargo:warning=compilation terminated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "arm-linux-androideabi-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wall" "-Wextra" "-o" "/home/ec2-user/arrow-client/target/arm-linux-androideabi/release/build/arrow-client-1f4c6dab72503398/out/src/net/raw/devices.o" "-c" "src/net/raw/devices.c" with args "arm-linux-androideabi-gcc" did not execute successfully (status code exit code: 1).

', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

I am searching a lot and see that ifaddrs.h not exists in android and there are some wrappers like this https://github.com/morristech/android-ifaddrs but I don't know how to add to the cargo build process.

**Comment by operutka** [comment]
Hi @gonzafirewall,
unfortunately, Android ABI is still not supported. You can try the following:

1. **use the develop branch** which is more up to date and should be more platform independent
2. clone the https://github.com/morristech/android-ifaddrs repository into the `src/ifaddrs` subdirectory of your Arrow Client tree
3. modify the build.rs script to make it look like this:

```rust
...

fn main() {
    Build::new()
        .include("src/ifaddrs")
        .file("src/ifaddrs/ifaddrs.c")
        .file("src/net/raw/devices.c")
        .compile("net_devices");

    if cfg!(feature = "discovery") {
        link("pcap");
    }
}

...
```

4. do not use the `--features discovery` flag when building the Arrow Client

Please, let me know if this solution works for you.

**Comment by gonzafirewall** [comment]
Ok that resolve partially, now I have 
`cargo:warning=src/net/raw/devices.c:131:31: error: 'SOCK_DGRAM' undeclared (first use in this function)`

but I resolved putting the socket header in the ifaddrs.h like this

```
...
  #endif
  
  #include <sys/cdefs.h>
+ #include <sys/socket.h>
  ..
```

Now I think that need the OpenSSL library for Android because of this

`--- stdout
cargo:rerun-if-env-changed=ARM_LINUX_ANDROIDEABI_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=ARM_LINUX_ANDROIDEABI_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=ARM_LINUX_ANDROIDEABI_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-unknown-linux-gnu
    $TARGET = arm-linux-androideabi
    openssl-sys = 0.9.24

', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.24/build.rs:210:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
`

I'll keep trying

**Comment by operutka** [comment]
Thanks for verifying the ifaddrs patch. I'll add it into the repo in one of the future releases.

Regarding the OpenSSL issue - yes, you really need OpenSSL for Android as it's one of the dependencies (the only one if you don't need the network scanner). You can either compile it on your own or you can use some existing package. However, the library itself is not enough. You'll also need OpenSSL header files. Once you get both, set the following environment variables:

```bash
# a path to libcrypto.so and libssl.so
export OPENSSL_LIB_DIR=/some/path/lib
# a path to a directory containing "openssl" subdirectory with OpenSSL header files
export OPENSSL_INCLUDE_DIR=/some/path/include
```

Good luck with your effort!

**Comment by gonzafirewall** [comment]
Compilled Ok with the last upgrade! Thanks!
