### ISSUE TITLE
Error compiling arrow client

### ISSUE THREAD

**Issue by wesoos** [angelcam/arrow-client#14]
Hello, I have successfully compiled and deployed many DIY angelboxes.  However, I'm trying to do one right now and I'm getting a compile error.  Please advise.  This is urgent...

error[E0599]: no method named `eq_ignore_ascii_case` found for type `&str` in the current scope
   --> src/config.rs:850:16
    |
850 |     if !scheme.eq_ignore_ascii_case("rtsp") {
    |                ^^^^^^^^^^^^^^^^^^^^
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            candidate #1: `use std::ascii::AsciiExt;`

error[E0599]: no method named `eq_ignore_ascii_case` found for type `&str` in the current scope
   --> src/config.rs:890:16
    |
890 |     if !scheme.eq_ignore_ascii_case("http") {
    |                ^^^^^^^^^^^^^^^^^^^^
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            candidate #1: `use std::ascii::AsciiExt;`

error: aborting due to 2 previous errors

error: Could not compile `arrow-client`.

**Comment by operutka** [comment]
Hi @wesoos,
this is due to a breaking change in the latest version of Rust. Update to Rust 1.23.0 and everything should work again.

**Comment by wesoos** [comment]
Hi, I run `curl https://sh.rustup.rs -sSf | sh` and it install 1.21.0

How do I upgrade?  If I run `sudo apt-get update && sudo apt-get dist-upgrade` it doesnt give me anything to upgrade

**Comment by operutka** [comment]
Have you tried the following?
```bash
rustup update
```

**Comment by wesoos** [comment]
I get command not found

**Comment by operutka** [comment]
OK, make sure that you don't have two conflicting installations of Rust. At first, make sure that the installation using curl is in your PATH:
```bash
export PATH=$HOME/.cargo/bin:$PATH
```

then uninstall everything:
```bash
rustup self uninstall
sudo apt-get purge rust*
```

then install it again:
```bash
curl https://sh.rustup.rs -sSf | sh
```

**Comment by wesoos** [comment]
Thanks it worked!
