### ISSUE TITLE
It don´t boot on Raspberry 3B+

### ISSUE THREAD

**Issue by LiJu09** [angelcam/arrow-client#18]
Please make it compatible with Raspberry 3B+

Thanks

**Comment by operutka** [comment]
Hi @LiJu09,
what exactly does not work in your case? Our image is compatible with all Raspberry Pi 2/3 models. Please follow [these](https://github.com/angelcam/arrow-client/wiki/Turning-your-ARM-device-into-AngelBox) instructions step by step to install Arrow Client into your device. If you're using our image, make sure that you use the `angel-box-rpi-*.img.zip`, the `angel-box-opi-*.img.zip` version is for Orange Pi Zero.

**Comment by operutka** [comment]
Hi again @LiJu09,
I've checked it again and there really is a problem with Raspberry Pi 3B+. Raspberry Pi 3B works fine though, so there must have been some breaking change between these two models. There is a new image available [here](https://github.com/angelcam/arrow-client/releases/tag/v0.8.0). The new image should work fine with all Raspberry Pi models starting from version 2.
