### ISSUE TITLE
Raspberry 3B+ QR code scanning

### ISSUE THREAD

**Issue by LiJu09** [angelcam/arrow-client#19]
When I am want scan QR code I see only black screen.

![screenshot_2018-07-22 angelcam pair your device](https://user-images.githubusercontent.com/40698774/43047186-e9fbe520-8dd3-11e8-8bde-0353b9a19c68.png)

Please help

**Comment by operutka** [comment]
Hi @LiJu09,
this does not seem to be a technical issue with Arrow Client. It highly depends on your camera. Even though we do our best to support all kinds of cameras, sometimes the camera streams are too buggy to be played in our player. Please contact our support team via the blue bubble in bottom right corner on my.angelcam.com (you need to be logged in). They will be happy to help you.
