### ISSUE TITLE
Option to log to stdout instead of syslog please

### ISSUE THREAD

**Issue by thomaslea** [angelcam/arrow-client#2]
One of my embedded targets has a syslog configuration that for various reasons I do not want the arrow client to use.  It would be great if there was a buildtime or runtime option to log to stdout instead.

**Comment by operutka** [comment]
No problem. I'll add the feature. However, I think a better idea is to log into stderr instead of stdout. Is there any reason why you want it in stdout?

**Comment by thomaslea** [comment]
Meh, I don't care too strongly about which stream.  Stderr seems a bit odd, but that's your call of course.

Now that I think of it more, it would be better if it were a runtime option instead of compile time... makes debugging it easier if you normally want it to use syslog.

Thanks!
Thomas

**Comment by operutka** [comment]
I didn't even consider making it a compile time option ;)

**Comment by operutka** [comment]
It's in the master. I'll make a new tagged release some day next week. You can switch it either by `--log-stderr` or `--log-stderr-pretty`. The first argument just enables logging into stderr, the second one also adds some colors.

**Comment by thomaslea** [comment]
Nice! I'll check it out.

Thanks,
Thomas
