### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Fault87** [angelcam/arrow-client#20]
Hello,

I'm trying to install the arrow-box client from the APT repository on my raspberry Pi 3, but I get the following error:

xxxxxxx : sudo apt-get install arrow-box
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 arrow-box : Depends: libssl1.1 but it is not installable
E: Unable to correct problems, you have held broken packages.

The Os version is: Raspbian GNU/Linux 8 (jessie)

Thank you.
Regards.

**Comment by operutka** [comment]
Hi @Fault87,
it seems that you're trying to install a version of the arrow-box packege that has been built for Raspbian 9 (i.e. stretch). You can either update your OS or you can switch the Angelcam APT repository to the Jessie version by:
```
sudo sh -c 'echo "deb http://apt.angelcam.com/raspbian-jessie stable main" > /etc/apt/sources.list.d/arrow.list'
sudo apt-get update
```
