### ISSUE TITLE
Libav

### ISSUE THREAD

**Issue by windl** [angelcam/arrow-client#3]
Hi,

currently - I write a java media framework.
Please have a look on my draft homepage http://htpc-mediagate.de/homepage/live/.

The question is - is your libav project currently working?
Are you interessted in to help me and would you like to bring your project as movieplayer together with my project?

If yes, please send me an email to info@cosores.de

Thank you for your help
Uwe

**Comment by operutka** [comment]
Hi Uwe,

your project seems interesting. However, I see only a lot of "lorem ipsums". Could you tell me something more about it? What is it? A device? A piece of software?

Arrow Client is not related to Libav in any way. I think you mean the jlibav project. Unfortunately, jlibav has been discontinued as I don't have time to work on it anymore. It works with Libav 0.7, 0.8 and 9 and there is some basic support for Libav 10 but it's buggy. Feel free to fork the project and continue working on it if you like.

**Comment by windl** [comment]
Hi,the software (MediaGate) was initiated and written by myself. The whole software is written in Java. As videoplayer – I have embedded MPlayer. MPlayer is running in slave mode. In this case, it is not possible to draw something on a video. Couple of weeks ago – I started a small project using ffmpeg. FFmpeg is writing the picture and sound information to the standard out. A pipe reader is reading this information and shows the picture and play the sound. The problem is that HD videos are stutter.During this project I found your libav implementation. I was not able to compile your project without errors. It will be very helpful to move forward with your libav project.If not, is it possible to send me the existing project with all necessary dependencies and descriptions?Thank youUweOndřej Perutka notifications@github.com hat am 14. März 2016 um 09:42 geschrieben:Hi Uwe,your project seems interesting. However, I see only a lot of "lorem ipsums". Could you tell me something more about it? What is it? A device? A piece of software?Arrow Client is not related to Libav in any way. I think you mean the jlibav project. Unfortunately, jlibav has been discontinued as I don't have time to work on it anymore. It works with Libav 0.7, 0.8 and 9 and there is some basic support for Libav 10 but it's buggy. Feel free to fork the project and continue working on it if you like.—Reply to this email directly or view it on GitHub.

**Comment by operutka** [comment]
All necessary dependencies are specified in the pom.xml files. There are no extra dependencies. However, some of the dependencies might be broken as it's been some time since I abandoned the project. If you need a help with compilation, file a new issue directly to the [jlibav](https://github.com/operutka/jlibav) project (not here) and post there a complete Maven output.
