### ISSUE TITLE
[Feature request] Add version command

### ISSUE THREAD

**Issue by BKPepe** [angelcam/arrow-client#44]
I could not find any possibility to see the version of installed angelcam-connector on the router, and also, if I start angelcam-connector via init.script on the router and while checking log, I see that Arrow Client was started, but there is missing the version. I checked the help and I could not see it there.

```
Aug 21 23:25:54 turris angelcam-connector[6997]: 2022-08-22 01:25:54 INFO    [src/client.rs:307] Arrow Client started (uuid: foo, mac: foo)
```

Thereby, I ask if there is a possibility to add the option to check the version of angelcam-connector by issuing ``--version`` or ``-version`` command.

**Comment by operutka** [comment]
Sure thing. I agree it'd be useful. I'll add the option.

**Comment by BKPepe** [comment]
Thanks.
