### ISSUE TITLE
Unable to save client configuration: no such file or directory

### ISSUE THREAD

**Issue by BKPepe** [angelcam/arrow-client#45]
If I run ``angelcam-connector --help`` or even ``angelcam-connector --test``, I can see this error message:

```
ERROR: unable to save client configuration: No such file or directory (os error 2)
```

But after this error, I can see the usage and options, but the error could be quite confusing as I don't know, if I am able to fix this somehow on my end or which folder /file it can not find.

**Comment by operutka** [comment]
I agree the error message does not contain all the necessary information on its own. Though you could find out the path in the application usage (it's the default value for the `--config-file` parameter), it'd be better if the error message was more explicit.

**Comment by operutka** [comment]
#46 fixes the issue. Please note that if you run `angelcam-connector --help`, you'll still see the error message because the application expects the first argument to be a positional argument containing a hostname, so it'll treat `--help` as a hostname.

**Comment by BKPepe** [comment]
I'll check it tommorow.

Dne po 22. 8. 2022 17:36 uživatel Ondřej Perutka ***@***.***>
napsal:
