### ISSUE TITLE
Second camera

### ISSUE THREAD

**Issue by vrypan** [angelcam/arrow-client#5]
I have installed arrow-client on a RaspberryPi and connected my IP camera to angelicam. But I can not find how to connect a second camera, using the same RPi. Is there an option to enable a second stream?

**Comment by operutka** [comment]
Hi @vrypan,

how exactly did you install the Arrow client? How do you start it? Are you using the RPi image, the deb package or have you compiled the client on your own?

In case you've compiled the client on your own and you're asking how to start the client with more than one static service, it's fairly simple. You just need to add another `-r URL` or `-m URL` command line argument, e.g.:

```
arrow-client arr-rs.angelcam.com:8900 \
    ...
    -r "rtsp://10.0.0.1/my/first/camera" \
    -r "rtsp://10.0.0.2/my/second/camera" \
    -m "http://10.0.0.3/my/third/camera" \
    ...
```

or you can just leave the hard work for the network scanner.

If you're asking how to add more cameras to your Angelcam user account after you've done the pairing procedure, than the solution is a bit more messy. For security reasons, we don't allow to use a single MAC address multiple times for pairing. The device must be "unpaired" first. Currently, there is no easy way how to do it. We're working on a user-friendly solution but it'll take some time. We can do the unpairing for you. You just need to send an unpairing request together with your MAC address to our support.

After your device is unpaired, you have to get through the pairing procedure again and after scanning the QR code, select all cameras you want to add to your Angelcam account.

**Comment by operutka** [comment]
No response from the author. I assume the advice was helpful. I'm closing this issue...

**Comment by vrypan** [comment]
For the record:
- I was using the deb package.
- Angelcam support did unpair the devices, so I could start over. However, it was impossible to make both cameras pair at the same time. I'm sorry, I do not remember the exact issue, but it was something to do with the website part: I could see both cameras available, but could not pair them both, or something similar.
- So, unfortunately, I had to revert to exposing my cameras via NAT :-( and adding them directly to angelcam.com.

**Comment by operutka** [comment]
OK, just a follow-up - you should be able to add multiple cameras in one pairing step by following this procedure:
1. enter your MAC address
2. select a stream you'd like to use for pairing
3. point the corresponding camera to the displayed QR code and wait until it shows "success"
4. select all streams/cameras you'd like to add to your Angelcam account
5. click on the "Add" button at the bottom of the page

You don't have to pair every single stream/camera. The pairing procedure is designed to verify that you have direct access to the Arrow device. IP cameras are just tools for reading the QR code.

**Comment by jordancrawford** [comment]
I think I'm experiencing a similar issue. I am setting up a Docker image for the Arrow client. The network detection doesn't work for me (SIOCGIFHWADDR not finding a device) so I manually defined the RTSP cameras with command line options. Both cameras showed up in the pairing interface, however, when I pair one of them (only one of them is in a convenient location to provide the QR code), the camera is added successfully but I don't get any options to add the second camera (it just goes straight to the cameras page).

If there is something I'm doing wrong, some screenshots of what I'm meant to see would be helpful.
Worst case scenario I guess I could just run two Arrow clients, but its difficult to pair one of them and obviously that not an ideal solution.

My current progress on the Docker image is https://github.com/jordancrawfordnz/arrow-client-docker so you can see how I've installed it through the Dockerfile.

**Comment by operutka** [comment]
Thanks for reporting. There should definitely be an option to select multiple cameras after the QR step if there is more than one camera available. Someone will take a look at it.

**Comment by operutka** [comment]
I owe you an apology, guys. The feature for selecting multiple streams after the QR step is really missing on our web.

Unfortunately, we're migrating our web to a completely new technology, so we have no capacity to add this feature right now. It will be definitely added once our web is migrated. Until then, we can generate an AngelBox ID for you, so you can use your Arrow Client as a regular AngelBox. This ways you'll be able to add multiple streams.

Please, contact our support regarding the AngelBox ID and send them your Arrow Client UUID (you can find it in your logs). I'm sorry again for the confusion.

**Comment by jordancrawford** [comment]
Thanks for that, I will get a ID from support.

Could you comment here once it's fixed, I'll mention this issue in the documentation for my Docker Arrow client report.
