### ISSUE TITLE
Orange Pi Zero

### ISSUE THREAD

**Issue by dehatter** [angelcam/arrow-client#55]
Not really an issue but just confirming that the last available release for OPI is 6/1/2020?

There are releases for RPI after this date, but I do not see one for OPI.

Is there a method for using the RPI release on an OPI?

**Comment by operutka** [comment]
Yes, that's correct. We don't release firmware images for Orange Pi devices anymore. However, you can still install the Arrow Client APT packages to your device and create you own DIY AngelBox. The packages should work for any Debian derivative (e.g. armbian). See https://github.com/angelcam/arrow-client/wiki/Turning-your-ARM-device-into-AngelBox#installation-from-our-apt-repository for more details.
