### ISSUE TITLE
Configurable path to configuration files

### ISSUE THREAD

**Issue by VelkyVenik** [angelcam/arrow-client#6]
It would be nice to have the option to store config files also in different location than the system folder - /etc.  For example specify the path in command line argument or in json config file.

**Comment by operutka** [comment]
The client already supports this feature via the --config-file argument. Start the client with no arguments to see the full help.

**Comment by VelkyVenik** [comment]
I know I can configure the location of config.json, but can I also configure location of generated config files? In documentation there is - The application requires /etc/arrow directory for storing its configuration file generated on the first start. 

I'm not a Rust specialist but it looks that this path is hardcoded and not parsed from command line arguments - man.rs function AppConfigurationParser.parse

**Comment by operutka** [comment]
/etc/arrow contains only the following files:
- config.json
- rtsp-paths
- mjpeg-paths

config.json is the configuration file generated on the first start. rtsp-paths and mjpeg-paths are not needed unless you enable the network scanner. Paths to all of these files can be changed using a command line parameter. main.rs contains only the default paths to these files.

**Comment by VelkyVenik** [comment]
Oops... You're right. How could I miss this.
