### ISSUE TITLE
Additional instructions would be nice

### ISSUE THREAD

**Issue by kevinlieb** [angelcam/arrow-client#7]
I am looking for additional instructions on the wiki like:
1. How do I start / stop the arrow service on a apt-get installed version on Raspberry Pi
2. How do I change startup parameters when running as a service
3. What are the startup parameters I can change
4. How do I force add a camera that is not being autodetected (in my case a Foscam mjpeg camera)

**Comment by kevinlieb** [comment]
5. how do I exclude a non-camera resource on the network that keeps getting detected as a camera
6. Where to see detailed debug logs when tracking down problems

**Comment by operutka** [comment]
Hi @kevinlieb,

1. The arrow-client service uses standard system mechanisms, i.e. systemd. To start/stop the service you can simply run:
```
sudo systemctl start arrow-box.service
sudo systemctl stop arrow-box.service
```
2. You can change the parameters in the start script located in `/usr/bin/arrow-box`.
3. Simply run the arrow-client executable without any parameters to get the list of all parameters, i.e.:
```
/usr/local/arrow-box/arrow-client
```
4. You can use the startup parameters (`-r` or `-m` in this case).
5. Currently, it is not possible to exclude anything from autodetection. However, it'd be a good idea to have something like this in one of the upcoming versions. It shouldn't be a big problem for you as autodetection alone does not mean anything. You can only see the false-positives in the list of detected devices but you don't have to add these devices into your Angelcam dashboard.
6. Again - we use standard system mechanisms, so all the logs go into syslog (i.e. `/var/log/syslog`). If you need higher verbosity, you can add `-v` as one of the startup parameters.

Anyway, thanks for your questions! I'll make some help text out of it and add it to the wiki.
