### ISSUE TITLE
DIY

### ISSUE THREAD

**Issue by wesoos** [angelcam/arrow-client#9]
Hello, I'm attempting to create our own AngelBox with a more powerful PC.  We installed Ubuntu 16.4, and followed the Quick Start guide step by step.  It all seems to have installed fine, however we are not able to add cameras from AngelCam that is on the same network.  I get the following message:

"We are connected to your device but we haven't found any cameras in your local network."

So I got a few questions:

- What do I need to do to look into this issue and figure out why it won't find cameras?

- I see this in the logfile:  "unable to save current connection state (No such file or directory (os error 2))".  What does that mean?

- How do I turn "arrow-client" into a service to run in background and start after a system reboot.

- I compiled the program with "discovery", do I also need the "-d" command when running?  When I do that it almost stops immediately with "Segmentation fault (core dumped)
" and in the log I see "segfault at 88 ip 00007f762b44c174 sp 00007f76289f8f00 error 4 in libpcap.so.1.7.4[7f762b43c000+3e000]"

Thanks
Wessel

**Comment by operutka** [comment]
Hi @wesoos,

the problem really is in the `-d` parameter. Network scanning is disabled by default and you need to turn it on using the `-d` parameter. The segfault you get, however, is quite unfortunate. We use the Arrow client on Ubuntu 16.04 x86_64 with libpcap 1.7.4 without any problems, so we'll need a little bit more info from you to reproduce this bug and to fix it.

We need to know which version of Rust compiler you're using, what architecture you're building for and the exact steps that you use to compile the Arrow client.

The "unable to save current connection state..." message simply means that the client cannot write into the connection state file. The file can be used by third party applications for reporting connection state of the Arrow client. However, the client does not depend on this feature and you can ignore the message.

Turning the Arrow client into a service is beyond our scope and it depends on the environment it's used in. In your case, it should be quite easy. You just need to create a run script and a systemd unit file. If you don't know how to create unit files, take a look here: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sect-Managing_Services_with_systemd-Unit_Files.html

**Comment by wesoos** [comment]
Thanks for the reply.  I'm not a linux expert, but I followed the exact steps in your Quick Start guide.

For Rust I did "curl https://sh.rustup.rs -sSf | sh"  so I'm assuming that's latest version.

When compiling the client, I do a "cargo build --features "discovery"  in the "arrow-client" directory.

I'm not sure which architecture I'm building for, as I don't believe I specify that anywhere.

Thanks

**Comment by wesoos** [comment]
Also, how do I check the libpcap version?

To install I did a "sudo apt-get install libpcap-dev" per your guide.

**Comment by wesoos** [comment]
Libpcap 1.7.4-2

**Comment by wesoos** [comment]
I created a bash script, executable, to run the arrow-client with options.  Then I followed your link to create a custom unit file.  It seems to start up at first, but then stops claiming it timed out.  How can I get past this?

**Comment by wesoos** [comment]
Ok I got the arrow-client running as a service.  So I'm good there.  Just need to figure out the "-d" flag now

**Comment by operutka** [comment]
We really need the version of your Rust compiler. You can get it using the following command:
```
rustc --version
```

Your network configuration would be also helpful. You can get it using:
```
ip address list
```

Could you also attach your Arrow client binary? We'll take a better look at it.

**Comment by wesoos** [comment]
Rust version:
rustc 1.17.0 (56124baa9 2017-04-24)

IP Info:

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group defaul                                                                                                                                                             t qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP                                                                                                                                                              group default qlen 1000
    link/ether 50:9a:4c:3f:d8:0d brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.73/24 brd 192.168.1.255 scope global enp2s0
       valid_lft forever preferred_lft forever
    inet6 2601:cc:80:c16:529a:4cff:fe3f:d80d/64 scope global mngtmpaddr dynamic
       valid_lft 306218sec preferred_lft 306218sec
    inet6 fe80::529a:4cff:fe3f:d80d/64 scope link
       valid_lft forever preferred_lft forever
3: wlp3s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default ql                                                                                                                                                             en 1000

    link/ether 28:16:ad:7f:b3:40 brd ff:ff:ff:ff:ff:ff

Arrow-client attached:
[arrow-client.zip](https://github.com/angelcam/arrow-client/files/992979/arrow-client.zip)

**Comment by wesoos** [comment]
What version of Rust should I use?

**Comment by operutka** [comment]
Thanks, I'll take a look at it.

There is no requirement on a particular version of Rust. It should always work with the latest version and it should work with your version as well. I just need to know exactly what version you're using in order to reproduce your problem and to fix it.

**Comment by wesoos** [comment]
Any word on this?

**Comment by operutka** [comment]
I've managed to reproduce your problem. It seems it segfaults when you don't have enough permissions to switch your network interfaces into promiscuous mode. I've created a fix. I'll push it into the repository later today.

However, you'll still need sufficient user permissions for using the network scanner. You can either run the client as root, which is the default behavior when you start the client using systemd, or you can add CAP_NET_RAW capability to the Arrow client binary. See the following links for more details:

https://linux.die.net/man/8/setcap
https://linux.die.net/man/7/capabilities

**Comment by operutka** [comment]
It has turned out there was a one more problem in the network scanner. I'm sorry for the confusion. It should be fixed now. Please, check the latest release and let me know if it works.

**Comment by wesoos** [comment]
Thanks, to recompile do I just grab the latest code via a git command?

Thanks
________________________________

**Comment by operutka** [comment]
Yes, exactly. Just do the following in the project root:
```
git pull origin
cargo build --features "discovery"
```

**Comment by operutka** [comment]
@wesoos Is this issue still valid or can I close it?

**Comment by wesoos** [comment]
You can close it, thanks.
